// @ts-check
import { defineConfig, fontProviders } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';

const MATERIAL_SYMBOL_NAMES = [
  'ac_unit',
  'accessible',
  'accessible_forward',
  'arrow_drop_down',
  'arrow_forward',
  'arrow_upward',
  'block',
  'business_center',
  'calendar_month',
  'campaign',
  'cancel',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'child_friendly',
  'close',
  'contrast',
  'dark_mode',
  'departure_board',
  'device_thermostat',
  'directions_bike',
  'directions_railway',
  'dynamic_feed',
  'emergency_home',
  'error',
  'expand_more',
  'family_restroom',
  'history',
  'hourglass_empty',
  'info',
  'language',
  'light_mode',
  'link_off',
  'location_on',
  'menu',
  'open_in_new',
  'published_with_changes',
  'refresh',
  'restaurant',
  'route',
  'schedule',
  'swipe',
  'timer',
  'today',
  'train',
  'trending_flat',
  'update',
  'verified',
  'view_carousel',
  'visibility',
  'warning',
  'wc',
].sort();

export default defineConfig({
  output: 'static',
  site: 'https://bellotreno.org',

  fonts: [
    {
      provider: fontProviders.google(),
      name: 'Inter',
      cssVariable: '--font-inter',
      weights: [400, 500, 600, 700],
      styles: ['normal'],
      subsets: ['latin'],
      display: 'swap',
      fallbacks: [],
    },
    {
      provider: fontProviders.google(),
      name: 'Outfit',
      cssVariable: '--font-outfit',
      weights: [400, 500, 600, 700, 800, 900],
      styles: ['normal'],
      subsets: ['latin'],
      display: 'block',
      fallbacks: [],
    },
    {
      provider: fontProviders.google(),
      name: 'JetBrains Mono',
      cssVariable: '--font-jetbrains-mono',
      weights: [400, 700],
      styles: ['normal'],
      subsets: ['latin'],
      display: 'swap',
      fallbacks: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
    },
    {
      provider: fontProviders.google(),
      name: 'Share Tech Mono',
      cssVariable: '--font-share-tech-mono',
      weights: [400],
      styles: ['normal'],
      subsets: ['latin'],
      display: 'swap',
      fallbacks: ['monospace'],
    },
    {
      provider: fontProviders.google(),
      name: 'Noto Sans SC',
      cssVariable: '--font-noto-sans-sc',
      weights: [400, 500, 700],
      styles: ['normal'],
      subsets: ['chinese-simplified', 'latin'],
      display: 'swap',
      fallbacks: ['PingFang SC', 'Microsoft YaHei', 'Noto Sans CJK SC', 'sans-serif'],
    },
    {
      provider: fontProviders.googleicons(),
      name: 'Material Symbols Outlined',
      cssVariable: '--font-material-symbols-outlined',
      display: 'block',
      fallbacks: [],
      options: {
        experimental: {
          glyphs: [MATERIAL_SYMBOL_NAMES.join(',')],
        },
      },
    },
  ],

  vite: {
    plugins: [tailwindcss()],
  },

  integrations: [
    sitemap({
      // 单 URL 多语言，无需 i18n 路由，直接列出所有页面
      filter: (page) => !page.includes('/_'),
    }),
  ],
});
