export {};

type Language = NonNullable<Window["currentLang"]>;
type AboutSection = "intro" | "roadmap" | "technical" | "official" | "disclaimer";
type AboutContent = Record<AboutSection, string>;

const linkClass = "text-primary no-underline hover:underline font-medium";

function link(href: string, label: string): string {
    return `<a href="${href}" target="_blank" rel="noopener noreferrer" class="${linkClass}">${label}</a>`;
}

const content: Record<Language, AboutContent> = {
    zh: {
        intro: `<p>BelloTreno 是一个由铁路爱好者制作的个人项目，旨在更清晰地展示意大利铁路列车运行、车站到发、出行公告、跨境编组和每日运行统计。相比 ${link("https://developers.deutschebahn.com/db-api-marketplace/apis/", "德国铁路 DB 开发者门户")}、${link("https://data.sncf.com/", "法国铁路 SNCF 开放数据")} 和 ${link("https://opentransportdata.swiss/en/", "瑞士 OpenTransportData.swiss")}，意大利铁路数据的开放程度仍然有限；本站希望以可视化方式展示这些公开数据的价值与限制。</p>`,
        roadmap: `<p class="font-semibold text-base-content mb-3">目前仍需处理的问题：</p><ul class="list-disc pl-6 space-y-2 mb-6"><li>由于上游 API 问题，仍需修复 Bologna Centrale/AV 站台显示错误的情况。</li><li>部分地方铁路公司（SAD、TT、TFT、TUA、EAV、FUC 等）缺少稳定 API 覆盖，需要更多 RFI 信息支持。</li></ul><p class="font-semibold text-base-content mb-3">未来发展方向：</p><ul class="list-disc pl-6 space-y-2"><li>继续完善铁路运行统计，提高车站、关系和车次聚合的可解释性。</li><li>扩大可观测数据覆盖，尽量补全地方铁路和跨境列车信息。</li><li>持续改进瑞士跨境列车编组、站台扇区和车辆明细显示。</li><li>优化移动端和 PWA 体验，让常用查询在手机上更稳定易读。</li></ul>`,
        technical: `<p>特别感谢以下开源项目、博客和社区探索者，他们的工作是本项目得以诞生的基础：</p><ul class="list-disc pl-6 space-y-2 mt-4"><li>${link("https://github.com/MarcoBuster/railway-opendata", "MarcoBuster / railway-opendata")} 和 ${link("https://github.com/roughconsensusandrunningcode/TrainMonitor/wiki/API-del-sistema-Viaggiatreno", "roughconsensusandrunningcode / TrainMonitor")} 等项目提供了详细的 API 说明和思路。</li><li>关于开放数据问题的文章：${link("https://medium.com/@tert6996/open-data-ed-rfi-che-disastro-1d1b631aabef", "Open Data ed RFI: Che disastro.")} 和 ${link("https://medium.com/@albigiu/trenitalia-shock-non-crederete-mai-a-queste-api-painful-14433096502c", "+++TRENITALIA SHOCK+++ NON crederete MAI a queste API painful")}。</li></ul>`,
        official: `<p class="mb-4">如需获取官方原始信息或查询不受本站支持的列车：</p><p class="font-semibold text-base-content mt-6 mb-3">查询列车实时信息（通过列车号码）：</p><ul class="list-disc pl-6 space-y-2"><li>Trenitalia：${link("http://www.viaggiatreno.it/infomobilita/index.jsp", "ViaggiaTreno")} 或 Trenitalia app</li><li>Italo：${link("https://italoinviaggio.italotreno.com", "Italo in Viaggio")}</li><li>SNCF：${link("https://www.sncf-voyageurs.com/en/travel-with-us/booking-and-itinerary/search-by-train-number/", "SNCF Train Search")}</li><li>ÖBB：${link("https://fahrplan.oebb.at/webapp/", "ÖBB Fahrplan")}</li></ul><p class="font-semibold text-base-content mt-6 mb-3">意大利车站（FS）实时信息：</p><ul class="list-disc pl-6 space-y-2"><li>RFI 实时监控：${link("https://www.rfi.it/it/stazioni/pagine-stazioni/servizi-di-qualita/informazioni-al-pubblico/monitor-arrivi-partenze-live.html", "Monitor Arrivi/Partenze Live")}</li><li>车站时刻表：${link("https://www.rfi.it/it/stazioni/pagine-stazioni/servizi-di-qualita/informazioni-al-pubblico/quadri-orario-on-line.html", "Quadri Orario Online")}</li></ul>`,
        disclaimer: `<p class="mb-4">本站仅为个人研究及铁路爱好者交流所用，所有数据均来源于公开接口，本站不保证准确性、完整性、可用性或实时性。在罢工、天气异常等特殊情况下，请务必以车站站台显示和官方信息为准。目前仅支持 ViaggiaTreno 上可查询的列车。</p><p>如有问题或建议，欢迎通过邮件 <a href="mailto:ferrovie@bellotreno.org" class="${linkClass}">ferrovie@bellotreno.org</a> 联系我。</p>`
    },
    en: {
        intro: `<p>BelloTreno is a personal railway data project. It presents Italian train running data, station boards, disruption notices, cross-border formations, and daily operating statistics in a clearer interface. Compared with the ${link("https://developers.deutschebahn.com/db-api-marketplace/apis/", "Deutsche Bahn developer portal")}, ${link("https://data.sncf.com/", "SNCF open data")}, and ${link("https://opentransportdata.swiss/en/", "OpenTransportData.swiss")}, Italian railway data is still less open and harder to work with; this site tries to make available public data easier to inspect.</p>`,
        roadmap: `<p class="font-semibold text-base-content mb-3">Open issues:</p><ul class="list-disc pl-6 space-y-2 mb-6"><li>Fix incorrect platform display for Bologna Centrale/AV caused by upstream API quirks.</li><li>Some local railway companies (SAD, TT, TFT, TUA, EAV, FUC, etc.) still lack stable API coverage and need better RFI data support.</li></ul><p class="font-semibold text-base-content mb-3">Future directions:</p><ul class="list-disc pl-6 space-y-2"><li>Improve railway statistics quality and make station, relation, and train aggregates easier to understand.</li><li>Expand observable data coverage for local railway and cross-border services.</li><li>Continue improving Swiss cross-border formation, platform-sector, and vehicle-detail presentation.</li><li>Refine mobile and PWA usability for repeated everyday lookups.</li></ul>`,
        technical: `<p>Special thanks to the following open-source projects, blogs, and community explorers, whose work has been the foundation for this project:</p><ul class="list-disc pl-6 space-y-2 mt-4"><li>${link("https://github.com/MarcoBuster/railway-opendata", "MarcoBuster / railway-opendata")} and ${link("https://github.com/roughconsensusandrunningcode/TrainMonitor/wiki/API-del-sistema-Viaggiatreno", "roughconsensusandrunningcode / TrainMonitor")} provided detailed API documentation and insights.</li><li>Blog posts about open data issues: ${link("https://medium.com/@tert6996/open-data-ed-rfi-che-disastro-1d1b631aabef", "Open Data ed RFI: Che disastro.")} and ${link("https://medium.com/@albigiu/trenitalia-shock-non-crederete-mai-a-queste-api-painful-14433096502c", "+++TRENITALIA SHOCK+++ NON crederete MAI a queste API painful")}.</li></ul>`,
        official: `<p class="mb-4">For official information or to query trains not supported by this site:</p><p class="font-semibold text-base-content mt-6 mb-3">Real-time train information by train number:</p><ul class="list-disc pl-6 space-y-2"><li>Trenitalia: ${link("http://www.viaggiatreno.it/infomobilita/index.jsp", "ViaggiaTreno")} or Trenitalia app</li><li>Italo: ${link("https://italoinviaggio.italotreno.com", "Italo in Viaggio")}</li><li>SNCF: ${link("https://www.sncf-voyageurs.com/en/travel-with-us/booking-and-itinerary/search-by-train-number/", "SNCF Train Search")}</li><li>ÖBB: ${link("https://fahrplan.oebb.at/webapp/", "ÖBB Fahrplan")}</li></ul><p class="font-semibold text-base-content mt-6 mb-3">Italian station (FS) real-time information:</p><ul class="list-disc pl-6 space-y-2"><li>RFI real-time monitoring: ${link("https://www.rfi.it/it/stazioni/pagine-stazioni/servizi-di-qualita/informazioni-al-pubblico/monitor-arrivi-partenze-live.html", "Monitor Arrivi/Partenze Live")}</li><li>Station timetables: ${link("https://www.rfi.it/it/stazioni/pagine-stazioni/servizi-di-qualita/informazioni-al-pubblico/quadri-orario-on-line.html", "Quadri Orario Online")}</li></ul>`,
        disclaimer: `<p class="mb-4">This site is for personal research and railway enthusiast communication only. All data comes from public interfaces, and this site does not guarantee accuracy, completeness, availability, or real-time correctness. In special circumstances such as strikes or extreme weather, please rely on station platform displays and official information. Currently, only trains queryable on ViaggiaTreno are supported.</p><p>For any questions or suggestions, please contact me via email: <a href="mailto:ferrovie@bellotreno.org" class="${linkClass}">ferrovie@bellotreno.org</a>.</p>`
    },
    it: {
        intro: `<p>BelloTreno è un progetto personale dedicato ai dati ferroviari. Presenta in modo più chiaro circolazione dei treni italiani, tabelloni di stazione, avvisi, composizioni transfrontaliere e statistiche giornaliere. Rispetto al ${link("https://developers.deutschebahn.com/db-api-marketplace/apis/", "portale sviluppatori di Deutsche Bahn")}, agli ${link("https://data.sncf.com/", "open data SNCF")} e a ${link("https://opentransportdata.swiss/en/", "OpenTransportData.swiss")}, i dati ferroviari italiani restano meno aperti e più difficili da usare; questo sito prova a rendere più leggibili i dati pubblici disponibili.</p>`,
        roadmap: `<p class="font-semibold text-base-content mb-3">Problemi ancora aperti:</p><ul class="list-disc pl-6 space-y-2 mb-6"><li>Correggere la visualizzazione errata dei binari di Bologna Centrale/AV dovuta a particolarità delle API upstream.</li><li>Alcune imprese ferroviarie locali (SAD, TT, TFT, TUA, EAV, FUC, ecc.) non hanno ancora una copertura API stabile e richiedono un miglior supporto dai dati RFI.</li></ul><p class="font-semibold text-base-content mb-3">Sviluppi futuri:</p><ul class="list-disc pl-6 space-y-2"><li>Migliorare la qualità delle statistiche e rendere più chiari aggregati per stazioni, relazioni e treni.</li><li>Ampliare la copertura dei dati osservabili per servizi locali e transfrontalieri.</li><li>Continuare a migliorare composizioni, settori di marciapiede e dettagli veicolo dei treni transfrontalieri svizzeri.</li><li>Ottimizzare esperienza mobile e PWA per consultazioni frequenti.</li></ul>`,
        technical: `<p>Un ringraziamento speciale ai seguenti progetti open-source, blog ed esploratori della comunità, il cui lavoro è stato la base per questo progetto:</p><ul class="list-disc pl-6 space-y-2 mt-4"><li>${link("https://github.com/MarcoBuster/railway-opendata", "MarcoBuster / railway-opendata")} e ${link("https://github.com/roughconsensusandrunningcode/TrainMonitor/wiki/API-del-sistema-Viaggiatreno", "roughconsensusandrunningcode / TrainMonitor")} hanno fornito documentazione API dettagliata e approfondimenti.</li><li>Post di blog sui problemi dei dati aperti: ${link("https://medium.com/@tert6996/open-data-ed-rfi-che-disastro-1d1b631aabef", "Open Data ed RFI: Che disastro.")} e ${link("https://medium.com/@albigiu/trenitalia-shock-non-crederete-mai-a-queste-api-painful-14433096502c", "+++TRENITALIA SHOCK+++ NON crederete MAI a queste API painful")}.</li></ul>`,
        official: `<p class="mb-4">Per informazioni ufficiali o per interrogare treni non supportati da questo sito:</p><p class="font-semibold text-base-content mt-6 mb-3">Informazioni sui treni in tempo reale per numero di treno:</p><ul class="list-disc pl-6 space-y-2"><li>Trenitalia: ${link("http://www.viaggiatreno.it/infomobilita/index.jsp", "ViaggiaTreno")} o app Trenitalia</li><li>Italo: ${link("https://italoinviaggio.italotreno.com", "Italo in Viaggio")}</li><li>SNCF: ${link("https://www.sncf-voyageurs.com/en/travel-with-us/booking-and-itinerary/search-by-train-number/", "Ricerca treni SNCF")}</li><li>ÖBB: ${link("https://fahrplan.oebb.at/webapp/", "ÖBB Fahrplan")}</li></ul><p class="font-semibold text-base-content mt-6 mb-3">Informazioni in tempo reale sulle stazioni italiane (FS):</p><ul class="list-disc pl-6 space-y-2"><li>Monitoraggio in tempo reale RFI: ${link("https://www.rfi.it/it/stazioni/pagine-stazioni/servizi-di-qualita/informazioni-al-pubblico/monitor-arrivi-partenze-live.html", "Monitor Arrivi/Partenze Live")}</li><li>Quadri orario di stazione: ${link("https://www.rfi.it/it/stazioni/pagine-stazioni/servizi-di-qualita/informazioni-al-pubblico/quadri-orario-on-line.html", "Quadri Orario Online")}</li></ul>`,
        disclaimer: `<p class="mb-4">Questo sito è solo per ricerca personale e comunicazione tra appassionati di ferrovie. Tutti i dati provengono da interfacce pubbliche e questo sito non garantisce accuratezza, completezza, disponibilità o correttezza in tempo reale. In circostanze speciali come scioperi o condizioni meteorologiche estreme, si prega di fare affidamento sui display delle piattaforme delle stazioni e sulle informazioni ufficiali. Attualmente sono supportati solo i treni interrogabili su ViaggiaTreno.</p><p>Per qualsiasi domanda o suggerimento, contattami tramite e-mail: <a href="mailto:ferrovie@bellotreno.org" class="${linkClass}">ferrovie@bellotreno.org</a>.</p>`
    }
};

function currentLanguage(): Language {
    return window.currentLang === "zh" || window.currentLang === "it" || window.currentLang === "en"
        ? window.currentLang
        : "en";
}

function renderAboutContent(): void {
    const language = currentLanguage();
    document.querySelectorAll<HTMLElement>("[data-about-section]").forEach((element) => {
        const section = element.dataset.aboutSection as AboutSection | undefined;
        if (section && content[language][section]) {
            element.innerHTML = content[language][section];
        }
    });
}

document.addEventListener("astro:page-load", renderAboutContent);
window.onLanguageChanged = renderAboutContent;
